services:
  wiremock:
    build:
      context: ./wiremock
      dockerfile: Dockerfile
    image: remita-wiremock:latest
    container_name: remita-wiremock
    ports:
      - "8090:8080"
      - "8443:8443"
    restart: unless-stopped
