# ── Android Desired Capabilities (Appium 2.x / W3C) ──────────────────────────

capabilities:
  platformName: "Android"
  "appium:automationName": "UiAutomator2"
  "appium:deviceName": "emulator-5554"
  "appium:platformVersion": "14"
  "appium:app": "../company-app/app-ta-debug_1.6.4.apk"
  "appium:appPackage": "com.cathayholdings.vdrf.ta"
  "appium:appActivity": "com.cathayholdings.vdrf.feature.splash.SplashActivity"
  "appium:noReset": false
  "appium:fullReset": false
  "appium:autoGrantPermissions": true
  "appium:newCommandTimeout": 300
  "appium:uiautomator2ServerInstallTimeout": 60000
  "appium:adbExecTimeout": 30000
